site_name: Web-программирование
site_url: https://KlimVladMaks.github.io/ITMO_ICT_WebDevelopment_2024-2025/
site_author: Владислав Клименков

theme:
  name: material
  language: ru

nav:
  - Главная: index.md
  - ЛР №1:
    - Задание 1: lab_1/task_1.md
    - Задание 2: lab_1/task_2.md
    - Задание 3: lab_1/task_3.md
